import { Link } from '@tanstack/react-router';
import { useState, type ReactNode } from 'react';
import { BookOpen, ArrowUpRight, Menu, X, MapPin, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
const navigation=[['Home','/'],['About Us','/about'],['Academics','/academics'],['Admissions','/admissions'],['Facilities','/facilities'],['Student Life','/student-life'],['Contact Us','/contact'],['Parent Portal Login','/portal']] as const;
export function SchoolBrand(){return <Link to="/" className="school-brand"><span className="crest"><BookOpen size={27}/></span><span><strong>Modern Public School</strong><small>Pratapgarh · Uttar Pradesh</small></span></Link>}
export function SchoolLayout({children}:{children:ReactNode}){const[open,setOpen]=useState(false);return <><a href="#main-content" className="skip-link">Skip to main content</a><div className="utility"><div className="container-school"><span className="flex items-center gap-2"><MapPin size={13}/> Chhatarur, Pratapgarh, Uttar Pradesh</span><span>A caring community. A brighter tomorrow.</span></div></div><header className="header-school"><div className="container-school"><div className="brand-row"><SchoolBrand/><Button asChild variant="outline" className="header-cta h-11"><Link to="/admissions">Begin your child’s journey <ArrowUpRight/></Link></Button><Button variant="ghost" size="icon" className="mobile-menu" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="school-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div><nav id="school-navigation" aria-label="Main navigation" className={`nav-school ${open?'is-open':''}`}>{navigation.map(([label,to])=><Link key={to} to={to} activeOptions={{exact:to==='/'}} activeProps={{className:'active'}} onClick={()=>setOpen(false)}>{to==='/portal'&&<LockKeyhole size={13} className="inline mr-2"/>}{label}</Link>)}</nav></div></header><main id="main-content">{children}</main><footer className="footer-school"><div className="container-school"><div className="footer-main"><div><SchoolBrand/><p>Nurturing curiosity, building character and inspiring a lifelong love of learning.</p><p className="flex gap-2"><MapPin size={17}/>Chhatarur, Pratapgarh, Uttar Pradesh</p></div><div><h3>Discover our school</h3><Link to="/about">About Us</Link><Link to="/academics">Academics</Link><Link to="/facilities">Facilities</Link><Link to="/student-life">Student Life</Link></div><div><h3>For families</h3><Link to="/admissions">Admissions</Link><Link to="/portal">Parent Portal</Link><Link to="/calendar">Academic Calendar</Link><Link to="/contact">Get in Touch</Link></div></div><div className="footer-bottom"><span>© 2026 Modern Public School, Pratapgarh</span><div className="flex gap-5"><Link to="/privacy">Privacy Notice</Link><span>Learning with care. Growing with purpose.</span></div></div></div></footer></>}
export function PageHeading({eyebrow,title,description}:{eyebrow?:string,title:string,description:string}){return <div className="page-heading"><div className="container-school"><div className="breadcrumbs"><Link to="/">Home</Link> <span className="mx-2">/</span> {title}</div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></div></div>}
export function JoinSchool(){return <section className="cta-school"><div className="container-school"><div><h2>A bright future begins with a first step.</h2><p>Let’s find the right learning journey for your child.</p></div><Button asChild variant="schoolGold" size="lg"><Link to="/admissions">Explore Admissions <ArrowUpRight/></Link></Button></div></section>}
export function ConceptPhoto({src,alt}:{src:string,alt:string}){return <figure><img src={src} alt={alt} width={1536} height={1024} loading="lazy"/><figcaption className="text-xs text-muted-foreground mt-2">Illustrative school imagery · actual campus photographs to follow</figcaption></figure>}
